version: "3.8"

services:

  # 🧭 API Gateway

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - board-service
      - action-service
      - snapshot-service
    networks:
      - app-network

  # 🔐 Auth Service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      PORT: "3001"
      MONGODB_URI: "mongodb://host.docker.internal:27017/authDb"
      ACCESS_TOKEN_SECRET: "change-me-access"
      REFRESH_TOKEN_SECRET: "change-me-refresh"
      ACCESS_TOKEN_TTL: "60m"
      REFRESH_TOKEN_TTL: "7d"
      COOKIE_SECURE: "false"
      COOKIE_SAMESITE: "strict"
      CORS_ORIGIN: "http://localhost:3000"

    networks:
      - app-network
    depends_on:
      - mongo

  # 📦 Board Service
  board-service:
    build: ./board-service
    container_name: board-service
    ports:
      - "3029:3029"
    environment:
      PORT: "3029"
      MONGODB_URI: "mongodb://host.docker.internal:27017/boardDb"
      KAFKA_BROKERS: "kafka:9092"
      KAFKA_BOARD_ACTIONS_TOPIC: "boards.actions"
      KAFKA_BOARD_INFO_TOPIC: "boards.info"
    depends_on:
      - kafka
      - mongo
    networks:
      - app-network

  #  Action Service
  action-service:
    build: ./action-service
    container_name: action-service
    ports:
      - "3035:3035"
    environment:
      PORT: "3035"
      WS_PATH: "/ws"
      ACCESS_TOKEN_SECRET: "change-me-access"
      KAFKA_BROKERS: "kafka:9092"
      KAFKA_CLIENT_ID: "action-service"
      KAFKA_ACTION_TOPIC: "actions"
      KAFKA_BOARD_ACTIONS_TOPIC: "boards.actions"
      KAFKA_BOARD_INFO_TOPIC: "boards.info"
      ACTIONS_HTTP_BASE_URL: "http://board-service:3029"
    depends_on:
      - kafka
      - board-service
    networks:
      - app-network

  # Snapshot Service
  snapshot-service:
    build: ./snapshot-service
    container_name: snapshot-service
    ports:
      - "3040:3040"
    environment:
      PORT: "3040"
      MONGODB_URI: "mongodb://mongo:27017/snapshotDb"
      KAFKA_BROKERS: "kafka:9092"
      KAFKA_BOARD_ACTIONS_TOPIC: "boards.actions"
      KAFKA_CONSUMER_GROUP_ID: "snapshot-service"
      SNAPSHOT_EVENT_THRESHOLD: "500"
      SNAPSHOT_INTERVAL_SECONDS: "10"
    depends_on:
      - kafka
      - mongo
    networks:
      - app-network


  # 📨 Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

    networks:
      - app-network

networks:
  app-network:
    driver: bridge