events {}

http {

    upstream auth_service {
        server auth-service:3001;
    }

    upstream board_service {
        server board-service:3029;
    }


    server {
        listen 80;

        # AUTH
        location /auth/ {
            proxy_pass http://auth_service;
        }

        # BOARD
        location /board/ {
            proxy_pass http://board_service/;
        }
    }
}